version: '3'

services:
  datastore:
    build:
      context: ./
      dockerfile: ./docker/datastore/Dockerfile
    environment:
      DATASTORE_PROJECT_ID: app
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - '8081:8081'
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    links:
      - 'datastore'
volumes: 
  node_modules_volume:
